
title: DrunkCode
email: contact@drunkcode.org
description: >
  DrunkCode is the union of two mobile programmers and at the same time two crazy dudes!
baseurl: ""
url: "http://drunkcode.org"
twitter_username: drunkcodeorg
github_username:  drunkcode

markdown: kramdown
exclude: [vendor]