
title: DrunkCode
email: contact@drunkcode.org
description: >
  DrunkCode is the union of two mobile programmers and at the same time two crazy dudes.
  The passion for developing and having a great time is the base for building this blog.
  Our focus is trying to show you the errors that we have done and how to avoid them without throw your computer out the window.
  Let’s do this together!
baseurl: ""
url: "http://drunkcode.github.io"
twitter_username: drunkcodeorg
github_username:  drunkcode

markdown: kramdown
exclude: [vendor]